name: 2. Build & Deploy to GCP

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    # Garante que só roda se você clicou em "Confirm Merge"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-central1
      REPO_NAME: meu-repo-docker # TEM QUE SER O MESMO NOME DO TERRAFORM

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1. Autenticação na Google Cloud
      - name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # 2. Configura o GCloud CLI
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      # 3. Autentica o Docker com o Artifact Registry
      - name: Docker Auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 4. Build e Push da Imagem Docker
      - name: Build and Push Container
        run: |
          TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/app:${{ github.sha }}"
          echo "Construindo imagem: $TAG"
          docker build -t $TAG .
          docker push $TAG
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # 5. Instala o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 6. Aplica a Infraestrutura
      # IMPORTANTE: O working-directory aponta para a pasta onde está o main.tf
      - name: Terraform Deploy
        working-directory: ./Terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="docker_image=${{ env.IMAGE_TAG }}"